# -*- coding: utf-8 -*-
# Copyright YEAR(S), AUTHOR(S)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

from . import settings
from . import util
from . import res_company
from . import res_partner
from . import product_product
from . import stock_picking
from . import account_invoice
from . import sale_order
from . import cfdi_fiel
from . import l10n_mx_immex_table
from . import l10n_mx_immex_table_type
from . import l10n_mx_immex_pedimento
from . import l10n_mx_immex_partida
from . import l10n_mx_immex_partida_type
from . import product_uom_factor
from . import l10n_mx_immex_partida_descargue
from . import l10n_mx_immex_customs
from . import mrp_bom
from . import l10n_mx_immex_code_pedimento
from . import l10n_mx_immex_customs_regimes
from . import l10n_mx_immex_resumen
from . import l10n_mx_immex_incidencias_reconocimiento
from . import l10n_mx_immex_partida_observaciones
from . import l10n_mx_immex_partida_contribuciones
from . import l10n_mx_immex_partida_tasas
from . import l10n_mx_immex_partida_garantias
from . import l10n_mx_immex_partida_casos
from . import l10n_mx_immex_partida_permisos
from . import l10n_mx_immex_mercancias
from . import l10n_mx_immex_pedimento_seleccion
from . import l10n_mx_immex_pedimento_diferencias
from . import l10n_mx_immex_pedimento_rectificaciones
from . import l10n_mx_immex_pedimento_destinatarios
from . import l10n_mx_immex_pedimento_descargos
from . import l10n_mx_immex_pedimento_observaciones
from . import l10n_mx_immex_pedimento_contribuciones
from . import l10n_mx_immex_pedimento_tasas
from . import l10n_mx_immex_pedimento_cuentas
from . import l10n_mx_immex_pedimento_casos
from . import l10n_mx_immex_pedimento_fechas
from . import l10n_mx_immex_pedimento_factura
from . import l10n_mx_immex_pedimento_factura_mercancia
from . import l10n_mx_immex_pedimento_contenedor
from . import l10n_mx_immex_pedimento_guia
from . import l10n_mx_immex_pedimento_transporte
from . import l10n_mx_immex_pedimento_documentos_digitalizados
