# -*- coding: utf-8 -*-
{
    'name': "Management system gebesa",
    'summary': "Management of corrective actions and contingency actions",
    'description': "Models for managing corrective actions and contingency actions in quality control",
    'author': "Marco Esquivel, Gebesa",
    'website': "http://www.yourcompany.com",
    'category': 'Uncategorized',
    'version': '0.1',
    'depends': ['base', 'message_post_model', 'hr', 'quality_control', 'sale', 'sale_order_gebesa'],
    'data': [
        'reports/report_actions.xml',
        'reports/report_change.xml',
        'reports/report_incidents.xml',
        'reports/report_daily_inspection.xml',
        'reports/xls_reports.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/quality_corrective_action_view.xml',
        'views/quality_contingent_actions_view.xml',
        'views/quality_corrective_action_lines_view.xml',
        'views/quality_change_management_view.xml',
        'views/quality_change_management_lines_view.xml',
        'views/quality_incidents_view.xml',
        'views/quality_contingent_incidents_view.xml',
        'views/quality_corrective_incidents_view.xml',
        'views/hr_department_view.xml',
        'views/quality_alert_view.xml',
        'views/quality_alert_flaw_view.xml',
        'views/mrp_workcenter.xml',
        'data/ir_sequence.xml',
        'data/email_template_action_corrective.xml',
        'wizards/sale_order_incidents.xml',
        # 'wizards/report_quality_alert_wizard.xml',
        'views/sale_order.xml',
        'data/ir_cron.xml',
    ],
    'demo': [
    ],
}
