# -*- coding: utf-8 -*-
# © <YEAR(S)> <AUTHOR(S)>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
{
    "name": "Freight Gebesa",
    "summary": "Freight Gebesa",
    "version": "12.0.1.0.0",
    "category": "Uncategorized",
    "website": "https://odoo-community.org/",
    "author": "Aldo Nerio, Gebesa",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "external_dependencies": {
        "python": [],
        "bin": [],
    },
    "depends": [
        "base",
        "tms",
        "mrp_shipment",
        "fuel_history_price",
        "message_post_model",
        "fleet",
        "product",
        "tms_tollstations",
        "mail",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/report_paperformat.xml",
        "data/waybill_mail_template.xml",
        "views/flete_route.xml",
        "views/mrp_shipment.xml",
        "views/tires.xml",
        "views/fleet_vehicle.xml",
        "views/travel.xml",
        "views/waybill.xml",
        "views/account_invoice.xml",
        "views/tms_travel_toallstation.xml",
        "views/tms_travel_stop.xml",
        "views/operating_unit.xml",
        "views/tms_expense.xml",
        "views/tms_event.xml",
        "views/fleet_vehicle_log_fuel_view.xml",
        "views/product_product.xml",
        "views/fleet_vehicle_event.xml",
        "views/hr_employee.xml",
        "views/hr_employee_event.xml",
        "views/res_partner.xml",
        "views/account_move_line.xml",
        "wizards/tms_wizard_invoice.xml",
        "wizards/tms_wizard_invoice_waybills.xml",
        "wizards/tms_wizard_validate.xml",
        "wizards/tms_wizard_tollstation.xml",
        "wizards/tms_wizard_tollstation_pase.xml",
        "wizards/account_export_bank_file_wizard.xml",
        "wizards/tms_wizard_real_amount.xml",
        "report/travel_instructions_2.xml",
        "report/carta_porte.xml",
        "report/carta_porte_travel.xml",
        "report/travel_expenses.xml",
        "report/mantenimiento_correctivo.xml",
        "report/informe_gastos.xml",
        "report/recibo_operador.xml",
        "report/stock_picking.xml",
        "views/gps_wsa_scanner.xml",
        "views/gps_wsa_scan_delete.xml",
        "views/stock_picking.xml",
        "views/tms_tire_position_hist_view.xml",
        "views/tms_hist_kms_traveled.xml",
        "views/dispersion_diesel_view.xml",
    ],
    "demo": [

    ],
    "qweb": [

    ]
}
