FROM debian:stretch-slim
MAINTAINER e-Fector <cesar.barron@gmail.com>

SHELL ["/bin/bash", "-xo", "pipefail", "-c"]

# Generate locale C.UTF-8 for postgres and general locale data
ENV LANG C.UTF-8

# Use backports to avoid install some libs with pip
RUN echo 'deb http://deb.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/backports.list

# Install some deps, lessc and less-plugin-clean-css, and wkhtmltopdf
RUN apt-get update \
        && apt-get install -y --no-install-recommends \
            ca-certificates \
            curl \
            git \
            dirmngr \
            fonts-noto-cjk \
            gnupg \
            libssl1.0-dev \
            node-less \
            python3-num2words \
            python3-pip \
            python3-phonenumbers \
            python3-pyldap \
            python3-qrcode \
            python3-renderpm \
            python3-setuptools \
            python3-slugify \
            python3-vobject \
            python3-watchdog \
            python3-xlrd \
            python3-xlwt \
            xz-utils \
            iputils-ping \
            python3-openssl \
            # libssl-dev \
            swig \
            python3-dev \
            gcc \
            m2crypto \
            libpq-dev \
            libsasl2-dev \
            libldap2-dev \
        && curl -o wkhtmltox.deb -sSL https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb \
        && echo '7e35a63f9db14f93ec7feeb0fce76b30c08f2057 wkhtmltox.deb' | sha1sum -c - \
        && apt-get install -y --no-install-recommends ./wkhtmltox.deb \
        && rm -rf /var/lib/apt/lists/* wkhtmltox.deb

# install latest postgresql-client
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' > /etc/apt/sources.list.d/pgdg.list \
        && GNUPGHOME="$(mktemp -d)" \
        && export GNUPGHOME \
        && repokey='B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8' \
        && gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "${repokey}" \
        && gpg --batch --armor --export "${repokey}" > /etc/apt/trusted.gpg.d/pgdg.gpg.asc \
        && gpgconf --kill all \
        && rm -rf "$GNUPGHOME" \
        && apt-get update  \
        && apt-get install --no-install-recommends -y postgresql-client \
        && rm -f /etc/apt/sources.list.d/pgdg.list \
        && rm -rf /var/lib/apt/lists/*

# Install rtlcss (on Debian stretch)
RUN echo "deb http://deb.nodesource.com/node_8.x stretch main" > /etc/apt/sources.list.d/nodesource.list \
    && GNUPGHOME="$(mktemp -d)" \
    && export GNUPGHOME \
    && repokey='9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280' \
    && gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "${repokey}" \
    && gpg --batch --armor --export "${repokey}" > /etc/apt/trusted.gpg.d/nodejs.gpg.asc \
    && gpgconf --kill all \
    && rm -rf "$GNUPGHOME" \
    && apt-get update \
    && apt-get install --no-install-recommends -y nodejs \
    && npm install -g rtlcss \
    && rm -rf /var/lib/apt/lists/*

RUN  apt-get -yq update && apt-get -yqq install ssh

# add credentials on build
ARG SSH_PRIVATE_KEY

RUN mkdir /root/.ssh/
RUN echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_ed25519
RUN chmod 600 /root/.ssh/id_ed25519

# make sure git domains is accepted
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan gitlab.e-fector.com >> /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

RUN echo "Host github.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
RUN echo "Host gitlab.e-fector.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config

# Create Odoo User in Ubuntu
RUN adduser --system --quiet --shell=/bin/bash --home=/home/odoo --gecos 'ODOO' --group odoo

# Clone repositories
RUN cd /opt/ && mkdir odoo && cd odoo
RUN chown -R odoo /opt/odoo/
RUN git clone --branch 12.0 git@gitlab.e-fector.com:gebesa/odoo_community_mirror.git /opt/odoo/12.0/
RUN git clone --branch 12.0 git@gitlab.e-fector.com:gebesa/odoo_enterprise_mirror.git /opt/odoo/enterprise/
RUN git clone --recurse-submodules --branch main git@github.com:cttox/gebesa.git /opt/odoo/gebesa
RUN mkdir /opt/odoo/log/

# Install external libraries
RUN pip3 install --no-cache-dir psycopg2-binary
RUN pip3 install --no-cache-dir wheel
RUN pip3 install --no-cache-dir -r /opt/odoo/12.0/requirements.txt
RUN pip3 install --no-cache-dir -r /opt/odoo/gebesa/addons-grupo-salmon/requirements.txt
RUN pip3 install --no-cache-dir -r /opt/odoo/gebesa/server-ux/requirements.txt
RUN pip3 install --no-cache-dir -r /opt/odoo/gebesa/web/requirements.txt
RUN pip3 install --no-cache-dir -r /opt/odoo/gebesa/reporting-engine/requirements.txt
RUN pip3 install --no-cache-dir -r /opt/odoo/gebesa/server-tools/requirements.txt
RUN pip3 install --no-cache-dir ipdb

# Copy entrypoint script and Odoo configuration file
COPY ./entrypoint.sh /
COPY ./odoo.conf /opt/odoo/
COPY ./odoo /etc/init.d/

# Mount /opt/odoo to allow restoring filestore and /mnt/extra-addons for users addons
RUN mkdir -p /mnt/extra-addons \
   && chown -R odoo /mnt/extra-addons
VOLUME ["/opt/odoo", "/mnt/extra-addons"]

# Expose Odoo services
EXPOSE 8069 8071 8072

# Set the default config file
ENV ODOO_RC /opt/odoo/odoo.conf

COPY wait-for-psql.py /usr/local/bin/wait-for-psql.py

# Set default user when running the container
USER odoo

ENTRYPOINT ["/entrypoint.sh"]
CMD ["odoo"]
# CMD ["odoo", "--config", "/opt/odoo/odoo.conf"]

# Build time 28:25