[options]
admin_passwd = @dmin?35078
addons_path = /opt/odoo/enterprise,/opt/odoo/gebesa/addons-grupo-salmon,/opt/odoo/gebesa/geospatial,/opt/odoo/gebesa/operating-unit,/opt/odoo/gebesa/reporting-engine,/opt/odoo/gebesa/cfdi32,/opt/odoo/gebesa/pentahoodoo,/opt/odoo/gebesa/server-ux,/opt/odoo/gebesa/multi-company,/opt/odoo/gebesa/e-commerce,/opt/odoo/gebesa/web,/opt/odoo/gebesa/stock-logistics-workflow,/opt/odoo/gebesa/stock-logistics-warehouse,/opt/odoo/gebesa/server-tools,/opt/odoo/gebesa/account-invoicing,/opt/odoo/gebesa/scrummergebesa,/opt/odoo/gebesa/knowledge,/opt/odoo/gebesa/management-system,/opt/odoo/gebesa/maintenance,/opt/odoo/gebesa/server-backend,/opt/odoo/gebesa/forkterceros
data_dir = /opt/odoo/datadir
;workers = 9
;max_cron_threads = 2
; admin_passwd = admin
; csv_internal_sep = ,
; db_maxconn = 64
; db_name = False
; db_template = template1
; dbfilter = .*
; debug_mode = False
; email_from = False
db_user = odoo
db_password = p3rrito.com
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
; limit_request = 8192
limit_time_cpu = 86400
limit_time_real = 86400
; list_db = True
; log_db = False
; log_handler = [':INFO']
; log_level = info
logfile = /opt/odoo/log/odoo-server.log
;longpolling_port = 8092
; max_cron_threads = 2
; osv_memory_age_limit = 1.0
; osv_memory_count_limit = False
; smtp_password = False
; smtp_port = 25
; smtp_server = localhost
; smtp_ssl = False
; smtp_user = False
; workers = 0
; xmlrpc = True
; xmlrpc_interface =
;xmlrpc_port = 8099
; xmlrpcs = True
; xmlrpcs_interface =
; xmlrpcs_port = 8071
