# -*- coding: utf-8 -*-
# © <YEAR(S)> <AUTHOR(S)>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
{
    "name": "immex_gebesa",
    "summary": "immex gebesa",
    "version": "12.0.1.0.0",
    "category": "Products",
    "website": "https://odoo-community.org/",
    "author": "Daniel Gurrola, Gebesa",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "external_dependencies": {
        "python": [],
        "bin": [],
    },
    "depends": [
        'base',
        'product',
        'stock',
        'account',
        'sale',
        'mx_locations',
        'foreign_commerce_complement',
        'stock_picking_type',
        "cfdi32",
        "l10n_mx_edi_external_trade_geb",
        "mrp",
        "global_chatter",

        # "system_administrator",
    ],
    "data": [
        "security/immex_security.xml",
        "security/ir.model.access.csv",
        "views/l10n_mx_immex_customs_view.xml",
        "views/res_company.xml",
        "views/res_partner.xml",
        "views/product_product.xml",
        "views/stock_picking.xml",
        "views/account_invoice.xml",
        "views/sale_order.xml",
        "wizard/import_data_stage_view.xml",
        "wizard/ws_pedimento_view.xml",
        "reports/input_product_report_view.xml",
        "wizard/input_product_wizard_view.xml",
        "data/l10n.mx.immex.table.type.csv",
        "views/l10n_mx_immex_resumen_view.xml",
        "views/l10n_mx_immex_partida_casos_view.xml",
        "views/l10n_mx_immex_partida_type_view.xml",
        "views/product_uom_factor_view.xml",
        "views/l10n_mx_immex_table_view.xml",
        "views/l10n_mx_immex_table_type_view.xml",
        "views/l10n_mx_immex_pedimento_view.xml",
        "views/l10n_mx_immex_pedimento_transporte_view.xml",
        "views/l10n_mx_immex_pedimento_guia_view.xml",
        "views/l10n_mx_immex_pedimento_contenedor_view.xml",
        "views/l10n_mx_immex_pedimento_factura_view.xml",
        "views/l10n_mx_immex_pedimento_fechas_view.xml",
        "views/l10n_mx_immex_pedimento_casos_view.xml",
        "views/l10n_mx_immex_partida_type_view.xml",
        "views/l10n_mx_immex_pedimento_cuentas_view.xml",
        "views/l10n_mx_immex_pedimento_tasas_view.xml",
        "views/l10n_mx_immex_pedimento_contribuciones_view.xml",
        "views/l10n_mx_immex_pedimento_observaciones_view.xml",
        "views/l10n_mx_immex_pedimento_descargos_view.xml",
        "views/l10n_mx_immex_pedimento_destinatarios_view.xml",
        "views/l10n_mx_immex_pedimento_rectificaciones_view.xml",
        "views/l10n_mx_immex_pedimento_diferencias_view.xml",
        "views/l10n_mx_immex_pedimento_seleccion_view.xml",
        "views/l10n_mx_immex_partida_view.xml",
        "views/l10n_mx_immex_mercancias_view.xml",
        "views/l10n_mx_immex_partida_permisos_view.xml",
        "views/l10n_mx_immex_partida_garantias_view.xml",
        "views/l10n_mx_immex_partida_tasas_view.xml",
        "views/l10n_mx_immex_partida_contribuciones_view.xml",
        "views/l10n_mx_immex_partida_observaciones_view.xml",
        "views/l10n_mx_immex_incidencias_reconocimiento_view.xml",
        "views/l10n_mx_immex_partida_descargue_view.xml",
        "views/cfdi_fiel_view.xml",
        "views/mrp_bom_view.xml",
        "views/res_company_view.xml",
        "reports/export_siimmex.xml",
        "views/l10n_mx_immex_code_pedimento_view.xml",
        "views/l10n_mx_immex_customs_regimes_view.xml",
        "data/l10n.mx.immex.customs.csv",
        "data/l10n.mx.immex.customs.regimes.csv",
        "data/l10n.mx.immex.code.pedimento.csv",
        "data/soap_vucem.xml",
        "data/ir_cron_data.xml",
        "wizard/corrections_initial_inventory_wizard.xml",
        "wizard/informe_descargos_wizard.xml",
        "reports/initial_inventory.xml",
        "reports/corrections_initial_inventory.xml",
        "reports/informe_descargos.xml",
        "reports/cove_to_pdf.xml",
        "reports/anexo24.xml",
        "wizard/report_anexo24_salida_merc_ws.xml",
    ],
    "demo": [
    ],
    "qweb": [
    ]
}
