# coding: utf-8
# Part of Odoo. See LICENSE file for full copyright and licensing details.

import base64
import logging

from lxml import objectify

from odoo import _, api, fields, models #, report
from odoo.exceptions import UserError
from odoo.tools.safe_eval import safe_eval

_logger = logging.getLogger(__name__)

try:
    from cfdilib import cfdv32
except ImportError as err:
    _logger.debug(err)


class PosSession(models.Model):
    _name = 'pos.session'
    _inherit = ['pos.session', 'mail.thread']

    @api.multi
    def create_xml_session(self):
        """Call methods that generate the invoice XML in the next cases:
        1.- The order was generated without customer, therefore without invoice
        2.- The order was generated with customer, but without invoice."""
        orders = self.order_ids.filtered(lambda r: not r.invoice_id)
        partners = orders.mapped('partner_id')._verify_mexican_data()
        order_filter = orders.filtered(
            lambda r: r.partner_id and r.partner_id.commercial_partner_id.id
            not in partners.ids and not r.xml_generated)
        if order_filter:
            res = order_filter.generate_xml_v32()
            self._generate_sesion_report(
                original_str=res.get('cfdi_cadena_original', False))
        order_filter = orders.filtered(
            lambda r: not r.partner_id and
            not r.xml_generated)
        if order_filter:
            res = order_filter.generate_xml_v32()
            self._generate_sesion_report(
                False, res.get('cfdi_cadena_original', False))

    @api.multi
    def reconcile_invoice(self):
        self.ensure_one()
        for order in self.order_ids.filtered('invoice_id'):
            bank_statement_ids = order.statement_ids.mapped(
                'journal_entry_ids').mapped('line_ids').filtered(
                    lambda dat:
                    dat.account_id.user_type_id.type == 'receivable')
            for bank_statement_id in bank_statement_ids:
                order.invoice_id.register_payment(bank_statement_id)
        return {}

    @api.multi
    def _generate_sesion_report(self, partner=True, original_str=False):
        """Generate the file PDF to session with data from last XML generated.
        If the report is generated to records without partners receive
        partner=False, and receive the value of original string to send to
        report to print in the PDF."""
        self.ensure_one()
        att_obj = self.env['ir.attachment']
        name = self.get_file_name(partner)
        attachment = att_obj.search([
            ('res_id', '=', self.id),
            ('res_model', '=', self._name),
            ('name', '=', name)], limit=1)
        # If not found XML, not must be generated the PDF
        if not attachment:
            return False
        # If found the XML, rename this to select the record to print, the
        # session could have two XML active.
        attachment.write({'name': ('%s_%s.xml' % (self.name, 'to_print'))})

        result, fformat = self.env.ref(
            'l10n_mx_pos.report_xml_session').with_context(
            cfdi_original_string=original_str).render(self.ids)
        # result, fformat = report.render_report(
        #     self.env.cr, self.env.uid, self.ids,
        #     'l10n_mx_pos.report_xml_session', {'model': self._name},
        #     context={'cfdi_original_string': original_str})
        # Return the original name after to generate the PDF file
        attachment.write({'name': name})
        name = self.get_file_name(partner, fformat, inc=True)
        att_obj.create({
            'name': name,
            'datas_fname': name,
            'datas': result and base64.encodestring(result) or None,
            'res_model': self._name,
            'res_id': self.id
        })
        return True

    @api.multi
    def _get_report_extra_data(self):
        return {}

    @api.multi
    def get_emitter_cfdi_v32(self):
        self.ensure_one()
        company = self.config_id.company_id
        address = company.address_parent_company_id._get_emmiter_address()
        address.update({
            'emitter_fiscal_position':
            company.partner_id.property_account_position_id.name,
            'emitter_name': company.name,
        })
        return address

    @api.multi
    def get_emitter_issued_on_cfdi_v32(self):
        self.ensure_one()
        address = self.config_id.company_id.partner_id
        return address._get_emitter_issued_address()

    @api.multi
    def get_receiver_cfdi_v32(self):
        """Return only the generic RFC to assign in the XML on receiver
        section, this is the unique value that is required in that section.
        The XML generated by this case have not partner related, or have not
        RFC, then is used this RFC."""
        return {
            'receiver_rfc': 'XAXX010101000',
            'receiver_country': self.env.ref('base.mx').name}

    @api.multi
    def action_pos_session_close(self):
        res = super(PosSession, self).action_pos_session_close()
        self.create_xml_session()
        return res

    @api.multi
    def cancelate_xml_session(self):
        """If the session have XML documents, try send to cancel in SAT system
        """
        att_obj = self.env['ir.attachment']
        for record in self:
            attach_xml_ids = att_obj.search([
                ('name', 'ilike', '%s%%.xml' % record.name.replace('/', '_')),
                ('res_model', '=', record._name),
                ('res_id', '=', record.id),
            ])
            invoice_obj = self.env['account.invoice']
            for att in attach_xml_ids.filtered('datas'):
                xml_string = base64.decodestring(att.datas)
                try:
                    xml = objectify.fromstring(xml_string)
                    uuid = invoice_obj.l10n_mx_edi_get_tfd_etree(
                        xml).get('UUID', '')
                except (AttributeError, SyntaxError, IndexError) as err:
                    _logger.error(err)
                    continue
                if not uuid:
                    continue
                certificate = record.config_id.company_id.certificate_id
                pac = self.config_id.journal_id.sequence_id.pac_id
                vx_res = invoice_obj._vauxoo_cancel(
                    pac, xml_string, certificate.file_pem,
                    base64.decodestring(certificate.file_key_pem),
                    certificate.password,
                )
                msg = vx_res.get('message') or ''
                if vx_res.get('cancellation_date', False):
                    msg += _(
                        '<br/> Cancellation date: %s' % vx_res[
                            'cancellation_date'])
                    orders = self.order_ids.filtered(
                        lambda r: not r.invoice_id and r.xml_generated)
                    if _('with_partner') in att.name:
                        orders.filtered(lambda r: r.partner_id).write({
                            'xml_generated': False
                        })
                    elif _('wo_partner') in att.name:
                        orders.filtered(lambda r: not r.partner_id).write({
                            'xml_generated': False
                        })
                if msg:
                    record.message_post(body=msg.replace('\n', '<br/>'))

    @api.multi
    def get_file_name(self, partner=True, ftype='xml', inc=False):
        """Return the file name, with a consecutive to duplicated names.
        Params:
            partner: Receive True if the file to generate contain the records
            that have partner reference, to set in the fail the label
            'with_partner'
            inc: Indicate if must be add the consecutive"""
        self.ensure_one()
        type_rec = _('wo_partner')
        if partner:
            type_rec = _('with_partner')
        session_name = self.name.replace('/', '_')
        fname = "%s_%s.%s" % (session_name, type_rec, ftype)
        if not inc:
            return fname
        count = self.env['ir.attachment'].search_count([
            ('name', '=', fname),
            ('res_model', '=', self._name),
            ('res_id', '=', self.id),
        ])
        if count > 0:
            fname = "%s_%s_%s.%s" % (session_name, type_rec, count + 1, ftype)
        return fname


class PosOrder(models.Model):
    _inherit = 'pos.order'

    xml_generated = fields.Boolean(
        'XML Generated', copy=False,
        help='Indicate if this order was consider in the session XML')

    @api.multi
    def generate_xml_v32(self):
        """Mapping cfdilib v3.2 - > Odoo
        The key is the name in the template on the cfdiv32.xml and the value
        for  the key is an attribute of an object account.invoice.
        The attribute can be a plain field or a method that returns an string
        You can use dot notation.
        To get the documentation into the cfdilib structure to convert you can
        go here : https://goo.gl/Xho6zK
        """
        if not self:
            return {}
        invoice_obj = self.env['account.invoice']
        session = self.mapped('session_id')
        company = session.config_id.company_id
        amount_total = 0.0
        subtotal = 0.0
        for order in self:
            amount_total += order.amount_total
            subtotal += order.amount_total - order.amount_tax
        invoice = {
            'currency': session.currency_id.name,
            'account': 'No identificado',
            'certificate': company.certificate_id.content_pem,
            'pay_method': 'No identificado',
            'date_invoice_tz': invoice_obj.datetime_cfdi(),
            'payment_policy': u'Pago en una sola exhibición',
            'number': session.name,
            'certificate_number': company.certificate_id.serial_number,
            'document_type': u'ingreso',
            'amount_total': amount_total,
            'subtotal_wo_discount': subtotal,
            'serie': 'NA',
            'invoice_lines': self._get_concepts_order(),
            'taxes': self.get_taxes_cfdi_v32()
        }
        invoice.update(session.get_emitter_cfdi_v32())
        invoice.update(session.get_emitter_issued_on_cfdi_v32())
        invoice.update(session.get_receiver_cfdi_v32())
        invoice = cfdv32.get_invoice(invoice)
        res = invoice_obj._vauxoo_stamp(
            invoice.document, session.config_id.journal_id.sequence_id.pac_id)\
            if not bool(invoice.ups) else {'error': invoice.ups.message}
        datas = res.get('cfdi_xml', '')
        ext = 'xml'
        generated = True
        if res.get('error'):
            datas = '%(message)s\n\n%(error)s' % ({
                'message': _('Error in XML generation!'),
                'error': res['error']})
            ext = 'log'
            generated = False
            _logger.error(res['error'])
        partner = False
        if self.mapped('partner_id'):
            partner = True
        name = session.get_file_name(partner, ext, inc=True)
        data_attach = {
            'name': name,
            'datas': base64.encodestring(datas.encode('utf8', 'ignore')),
            'datas_fname': name,
            'description': _('Orders in session %s.' % session.name),
            'res_model': session._name,
            'res_id': session.id,
        }
        if generated:
            self.write({'xml_generated': True})
        self.env['ir.attachment'].create(data_attach)
        return res

    @api.multi
    def _get_concepts_order(self):
        """With all pos.order that have not partner nor invoice, will be
        generated an XML with the same structure that XML invoice, and will be
        send to sign with the PAC.
        The XML signed will be attached in the session.
        """
        concepts = []
        for line in self.mapped('lines'):
            concepts.append({
                'name': line.product_id.name,
                'quantity': line.qty,
                'subtotal_wo_discount': line.price_subtotal_incl,
                'code': line.product_id.default_code or 'S/N',
                'unit': line.product_id.uom_id.name or 'NA',
                'price_unit': line.price_unit
            })
        return concepts

    @api.multi
    def get_taxes_values(self):
        tax_grouped = {}
        for line in self.mapped('lines'):
            price_unit = line.price_unit * (1 - (line.discount or 0.0) / 100.0)
            taxes = line.tax_ids_after_fiscal_position.compute_all(
                price_unit, line.order_id.session_id.currency_id, line.qty,
                line.product_id, line.order_id.partner_id)['taxes']
            for tax in taxes:
                tax_br = self.env['account.tax'].browse(tax['id'])
                val = {
                    'name': (tax_br.description or tax_br.name).upper(),
                    'tax_id': tax['id'],
                    'amount': tax['amount'],
                    'rate': tax_br.amount,
                }
                key = tax['id']
                if key not in tax_grouped:
                    tax_grouped[key] = val
                else:
                    tax_grouped[key]['amount'] += val['amount']
        return tax_grouped

    @api.multi
    def get_taxes_cfdi_v32(self):
        total_withhold = 0
        total_transferred = 0
        transferred_tax = []
        withhold_tax = []
        taxes = self.get_taxes_values()
        for tax in taxes.values():
            if tax.get('amount', 0.0) < 0:
                total_withhold += abs(tax.get('amount', 0.0) or 0.0)
                withhold_tax.append({
                    'name': tax.get('name'),
                    'amount': round(abs(tax.get('amount' or 0.0)), 2)})
                continue
            total_transferred += abs(tax.get('amount' or 0.0))
            transferred_tax.append({
                'name': tax.get('name'),
                'amount': round(abs(tax.get('amount' or 0.0)), 2),
                'rate': round(abs(tax.get('rate')), 2)
            })
        return {
            'total_withhold': total_withhold,
            'total_transferred': total_transferred,
            'withholding': withhold_tax,
            'transferred': transferred_tax}

    @api.multi
    def action_create_invoice(self):
        """When is created a new register, verify that partner have VAT, and
        create automatically the invoice."""
        for order in self:
            if (order.partner_id._verify_mexican_data() and
                    not order.invoice_id):
                order.action_pos_order_invoice()

    @api.multi
    def action_validate_invoice(self):
        """Validate the invoice after of opened."""
        self.mapped('invoice_id').action_invoice_open()

    def _get_main_order(self):
        """Used to get the main order that generated the return that you want
        to generate the invoice

        :return: The possible order that generated the return
        :rtype: pos.order()
        """
        self.ensure_one()
        return self.search([
            ('partner_id', '=', self.partner_id.id),
            ('sale_journal', '=', self.sale_journal.id),
            ('invoice_id', '!=', False),
            ('pos_reference', '=', self.pos_reference),
        ], order='date_order DESC', limit=1)

    @api.multi
    def prepare_credit_note(self):
        """Prepare the main values needed to create the credit note
        :return: The values of the new invoice
        :rtype: dict
        """
        self.ensure_one()
        if not self.partner_id:
            raise UserError(_('Please provide a partner for the sale.'))
        return {
            'name': self.name,
            'origin': self.name,
            'account_id': self.partner_id.property_account_receivable_id.id,
            'journal_id': self.sale_journal.id or None,
            'type': 'out_refund',
            'reference': self.name,
            'partner_id': self.partner_id.id,
            'comment': self.note or '',
            'currency_id': self.pricelist_id.currency_id.id,
            'company_id': self.company_id.id,
        }

    @api.multi
    def prepare_invoice_line(self, line):
        """Prepare the values for create an invoice_line
        :param line: Line of the order used to create the invoice line
        :type line: pos.order.line()
        :return: The values required to create a line
        :rtype: dict
        """
        self.ensure_one()
        return {
            'product_id': line.product_id.id,
            'quantity': abs(line.qty),
            'account_analytic_id': self._prepare_analytic_account(line),
            'name': line.product_id.name_get()[0][1],
            'price_unit': line.price_unit,
            'discount': line.discount
        }

    @api.multi
    def create_refund_from_existing_invoice(self):
        """Generate a credit note from an existing invoice with the wizard
        located in the invoice view
        :return: The new credit note generated
        :rtype: dict
        """
        self.ensure_one()
        date_mx = fields.Datetime.context_timestamp(
            self.with_context(tz='America/Mexico_City'),
            fields.Datetime.from_string(fields.Datetime.now()))
        main_order = self._get_main_order()
        if main_order.invoice_id.state not in ('paid', 'open'):
            return False
        invoice = main_order.invoice_id
        self.state = 'invoiced'
        if invoice.state == 'paid':
            journals = invoice.move_id.line_ids.filtered("reconciled")
            journals.remove_move_reconcile()
        refund_id = self.env['account.invoice.refund'].with_context(
            active_id=invoice.id, active_ids=[invoice.id],
            active_model='account.invoice').create({
                'filter_refund': 'cancel',
                'description': self.name,
                'date_invoice': date_mx,
            })
        action = refund_id.invoice_refund()
        for item in action.get('domain') or []:
            if len(item) == 3 and item[0] == 'id':
                self.invoice_id = (
                    item[2][0] if isinstance(
                        item[2], (list, tuple)) else item[2])
                break
        return action

    @api.multi
    def create_credit_note(self):
        """Generate a credit note for a return of products

        :return: Action to show the new invoice created
        :rtype: dict
        """
        invoices = self.env['account.invoice']
        inv_line_ref = self.env['account.invoice.line']
        company_id = self.company_id.id
        for order in self.with_context(
                force_company=company_id, company_id=company_id):
            if not order.partner_id:
                raise UserError(_('Please provide a partner for the sale.'))
            res = order.create_refund_from_existing_invoice()
            if res:
                return res
            inv = order.prepare_credit_note()
            invoice = invoices.new(inv)
            invoice._onchange_partner_id()
            invoice.fiscal_position_id = order.fiscal_position_id
            inv = invoice._convert_to_write(invoice._cache)
            inv_id = invoices.create(inv)
            order.write({'invoice_id': inv_id.id, 'state': 'invoiced'})
            invoices += inv_id
            for line in order.lines:
                inv_line = order.prepare_invoice_line(line)
                inv_line.update(invoice_id=inv_id.id)
                invoice_line = inv_line_ref.new(inv_line)
                invoice_line._onchange_product_id()
                taxes = (invoice_line.invoice_line_tax_ids.
                         filtered(lambda a: a.company_id.id == company_id))
                invoice_line.invoice_line_tax_ids = taxes
                fiscal_position_id = line.order_id.fiscal_position_id
                if fiscal_position_id:
                    taxes = fiscal_position_id.map_tax(
                        invoice_line.invoice_line_tax_ids)
                invoice_line.invoice_line_tax_ids = taxes
                inv_line = invoice_line._convert_to_write(invoice_line._cache)
                inv_line_ref.create(inv_line)
            inv_id.compute_taxes()
            order.state = 'invoiced'
            inv_id.action_invoice_open()
        if not invoices:
            return {}

        result = self.env.ref('account.action_invoice_tree1').read()[0]
        invoice_domain = safe_eval(result['domain'])
        invoice_domain.append(('id', 'in', invoice.ids))
        result['domain'] = invoice_domain
        return result

    @api.multi
    def action_pos_order_invoice(self):
        """Create a credit note if the order is a return of products"""
        refunds = self.filtered(lambda r: r.amount_total < 0)
        res_invoice = super(
            PosOrder, self - refunds).action_pos_order_invoice()
        res_id = res_invoice.get('res_id', False)
        res_note = refunds.create_credit_note()
        res_note_ids = [res_id] if res_id else []
        for item in res_note.get('domain') or []:
            if len(item) == 3 and item[0] == 'id':
                res_note_ids.extend(
                    item[2] if isinstance(item[2], (list, tuple)) and
                    item[2] else item[2])
                break
        # Because refund or invoice both use the same tree view
        result = self.env.ref('account.action_invoice_tree1').read()[0]
        invoice_domain = safe_eval(result['domain'])
        invoice_domain.append(('id', 'in', res_note_ids))
        result['domain'] = invoice_domain
        return result
