# -*- coding: utf-8 -*-
# Copyright 2016 Vauxoo (Moises Lopez <moylop260@vauxoo.com>)
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

from odoo import api, fields, models
# from odoo.exceptions import Warning as UserError


class PosOrder(models.Model):
    _inherit = 'pos.order'

    cogs_move_id = fields.Many2one('account.move', 'COGS Journal Entry',
                                   help='Journal entry generated to '
                                   'registered the COGS generated by '
                                   'the order', copy=False)

    @api.multi
    def generate_cogs_moves(self):
        """Generate cost journal entry for orders
        that does not contain invoice or a previous COGS journal entry"""
        self.ensure_one()
        session = self.session_id
        lines = (
            self.invoice_id.id is False and not self.cogs_move_id and not
            self._context.get('has_invoice', ()) and
            self.lines.filtered(lambda a: a.product_id.type != 'service' and
                                a.product_id.valuation == 'real_time') or ())
        if not lines:
            return True
        move_brw = self._create_account_move(session.start_at,
                                             self.name,
                                             session.config_id.journal_id.id,
                                             self.company_id.id)
        for line in lines:
            if (line.product_id.type != 'service' and
                    line.product_id.valuation == 'real_time'):
                ret = (self.amount_total > 0 and not
                       self._context.get('from_return', False) or False)
                sacc = (
                    line.product_id[ret and 'property_stock_account_output' or
                                    'property_stock_account_input'] or
                    line.product_id.categ_id[
                        ret and 'property_stock_account_output_categ_id' or
                        'property_stock_account_input_categ_id'])
                eacc = (line.product_id.property_account_expense_id or
                        line.product_id.categ_id.
                        property_account_expense_categ_id)
                total_cost = line.qty * line.product_id.standard_price
                line_vals = {
                    'name': line.product_id.name,
                    'move_id': move_brw.id,
                    'journal_id': move_brw.journal_id.id,
                    'date': move_brw.date,
                    'product_id': line.product_id.id,
                    'partner_id': self.partner_id.id,
                    'quantity': line.qty,
                    'ref': line.name
                    }
                caml = {
                    'account_id': (ret and sacc.id or eacc.id),
                    'credit': abs(total_cost),
                    'debit': 0.0,
                }
                caml.update(line_vals)
                daml = {
                    'account_id': (ret and eacc.id or sacc.id),
                    'credit': 0.0,
                    'debit': abs(total_cost),
                }
                daml.update(line_vals)
                move_brw.write({'line_ids': [(0, 0, caml),
                                             (0, 0, daml)]})

        move_brw.ref = self.name
        self.cogs_move_id = move_brw

    @api.multi
    def _create_account_move_line(self, session=None, move=None):
        """Posted all cost journal entries created for all orders related to
        the closed session
        """
        res = super(PosOrder, self)._create_account_move_line(session=session,
                                                              move=move)
        acc_move = self.mapped('cogs_move_id')
        acc_move.post()
        return res

    @api.multi
    def action_pos_order_invoice(self):
        """To avoid duplicate entries the Cost journal entries are removed at
        the moment to create the invoice because these journal items are
        created by the invoice automatically.
        """
        res = super(PosOrder, self).action_pos_order_invoice()
        res_note_ids = []
        for item in res.get('domain') or []:
            if len(item) == 3 and item[0] == 'id':
                res_note_ids.extend(
                    item[2] if isinstance(item[2], (list, tuple)) and
                    item[2] else item[2])
                break
        if res_note_ids:
            cogs_entries = self.mapped('cogs_move_id')
            cogs_entries.button_cancel()
            cogs_entries.unlink()
        return res

    @api.multi
    def refund(self):
        """Overwrite the refund method to adjust the Cost Journal Entry created
        by the main order. If the main order has an invoice related this method
        will send the id to avoid created cost journal entries for the order
        :return: The new order created(The return)
        :rtype: dict
        """
        no_create = self.filtered(lambda a: a.invoice_id).id and True
        self = self.with_context({'has_invoice': no_create,
                                  'from_return': True})
        res = super(PosOrder, self).refund()
        return res
