# -*- coding: utf-8 -*-
# © <YEAR(S)> <AUTHOR(S)>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

from odoo import api, fields, models


class AccountInvoice(models.Model):
    _inherit = 'account.invoice'

    is_additional = fields.Boolean(
        string='Is additional',
        index=False,
        help='It indicates whether this invoice was automatically'
             ' generated by being additional'
    )
    integration_id = fields.Many2one(
        'integration.cost.gebesa',
        string='integration',
        help='Integration which is linked to a purchase',
    )

    @api.multi
    def action_move_create(self):
        for inv in self:
            if inv.type == 'in_invoice':
                for line in inv.invoice_line_ids:
                    if line.product_id.landed_cost_ok is True:
                        inv.is_additional = True

        return super(AccountInvoice, self).action_move_create()
